##
# Azure Pipeline build file for a build using ubuntu and GCC5
#
# Copyright (c) 2019, Microsoft Corporation
# SPDX-License-Identifier: BSD-2-Clause-Patent
##
trigger:
- prtest/master
pr: 
- prtest/master

jobs:
- template: templates/pr-gate-build-job.yml
  parameters:
    tool_chain_tag: 'GCC5'
    vm_image: 'ubuntu-latest'
    arch_list: "IA32,X64,ARM,AARCH64"

